// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: logservice.proto

package logservice

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LogService service

func NewLogServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LogService service

type LogService interface {
	WriteLog(ctx context.Context, in *WriteLogRequest, opts ...client.CallOption) (*LogReply, error)
}

type logService struct {
	c    client.Client
	name string
}

func NewLogService(name string, c client.Client) LogService {
	return &logService{
		c:    c,
		name: name,
	}
}

func (c *logService) WriteLog(ctx context.Context, in *WriteLogRequest, opts ...client.CallOption) (*LogReply, error) {
	req := c.c.NewRequest(c.name, "LogService.WriteLog", in)
	out := new(LogReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LogService service

type LogServiceHandler interface {
	WriteLog(context.Context, *WriteLogRequest, *LogReply) error
}

func RegisterLogServiceHandler(s server.Server, hdlr LogServiceHandler, opts ...server.HandlerOption) error {
	type logService interface {
		WriteLog(ctx context.Context, in *WriteLogRequest, out *LogReply) error
	}
	type LogService struct {
		logService
	}
	h := &logServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LogService{h}, opts...))
}

type logServiceHandler struct {
	LogServiceHandler
}

func (h *logServiceHandler) WriteLog(ctx context.Context, in *WriteLogRequest, out *LogReply) error {
	return h.LogServiceHandler.WriteLog(ctx, in, out)
}
